/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Graphics2D.Plano;
import OperacionesMatematicas.Operaciones;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.WARNING_MESSAGE;

/**
 *
 * @author juand
 */
public class MenuPrincipal extends javax.swing.JFrame {
    private static MenuPrincipal menuP;
    public double carga1;
    public double carga2;
    public double distancia;
    public double fuerza;
    public boolean pantallaLimpia = false;
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        this.setResizable(false);
        setTitle("Ley de coulomb");
    }
    
    public static MenuPrincipal getMenuPrincipal(){
        if(menuP==null){
            menuP=new MenuPrincipal();
        }
        return menuP;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        conversionMedidas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCarga1 = new javax.swing.JTextField();
        txtCarga2 = new javax.swing.JTextField();
        txtDistancia = new javax.swing.JTextField();
        txtFuerza = new javax.swing.JTextField();
        botonCalcular = new javax.swing.JButton();
        BotonLimpiar = new javax.swing.JButton();
        BotonLimpiar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(99, 110, 114));

        jLabel7.setFont(new java.awt.Font("Tilt Warp", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(236, 240, 241));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Ley de coulomb");

        panel.setBackground(new java.awt.Color(236, 240, 241));
        panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        jLabel8.setFont(new java.awt.Font("Tilt Warp", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Grafica");

        conversionMedidas.setBackground(new java.awt.Color(236, 240, 241));
        conversionMedidas.setFont(new java.awt.Font("Tilt Warp", 0, 12)); // NOI18N
        conversionMedidas.setText("Conversion medidas");
        conversionMedidas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        conversionMedidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conversionMedidasActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tilt Warp", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(236, 240, 241));
        jLabel1.setText("Carga1 (C)");

        jLabel2.setFont(new java.awt.Font("Tilt Warp", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(236, 240, 241));
        jLabel2.setText("Carga2 (C)");

        jLabel3.setFont(new java.awt.Font("Tilt Warp", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(236, 240, 241));
        jLabel3.setText("Distancia (m)");

        jLabel4.setFont(new java.awt.Font("Tilt Warp", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(236, 240, 241));
        jLabel4.setText("Fuerza (N)");

        txtCarga1.setBackground(new java.awt.Color(236, 240, 241));

        txtCarga2.setBackground(new java.awt.Color(236, 240, 241));

        txtDistancia.setBackground(new java.awt.Color(236, 240, 241));

        txtFuerza.setBackground(new java.awt.Color(236, 240, 241));

        botonCalcular.setBackground(new java.awt.Color(236, 240, 241));
        botonCalcular.setFont(new java.awt.Font("Tilt Warp", 0, 12)); // NOI18N
        botonCalcular.setText("Calcular");
        botonCalcular.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        botonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalcularActionPerformed(evt);
            }
        });

        BotonLimpiar.setBackground(new java.awt.Color(236, 240, 241));
        BotonLimpiar.setFont(new java.awt.Font("Tilt Warp", 0, 12)); // NOI18N
        BotonLimpiar.setText("Limpiar");
        BotonLimpiar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BotonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLimpiarActionPerformed(evt);
            }
        });

        BotonLimpiar1.setBackground(new java.awt.Color(236, 240, 241));
        BotonLimpiar1.setFont(new java.awt.Font("Tilt Warp", 0, 12)); // NOI18N
        BotonLimpiar1.setText("Graficar magnitud");
        BotonLimpiar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BotonLimpiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLimpiar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(BotonLimpiar1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(jLabel8)
                                        .addGap(37, 37, 37))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                        .addComponent(jLabel3)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jLabel1)
                                                            .addComponent(jLabel2))
                                                        .addGap(47, 47, 47)))
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtDistancia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtCarga1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtCarga2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtFuerza, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(botonCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BotonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(29, 29, 29))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(conversionMedidas, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCarga1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtCarga2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(botonCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDistancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(BotonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFuerza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(conversionMedidas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BotonLimpiar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalcularActionPerformed
        // TODO add your handling code here:
        repaint();
        try {
            if(txtCarga1.getText().equals("")){
                carga2=Double.parseDouble(txtCarga2.getText());
                distancia=Double.parseDouble(txtDistancia.getText());
                fuerza=Double.parseDouble(txtFuerza.getText()); 
                txtCarga1.setText(Operaciones.calcularCarga(carga2,distancia,fuerza));
            }
            else if(txtCarga2.getText().equals("")){
                carga1=Double.parseDouble(txtCarga1.getText());
                distancia=Double.parseDouble(txtDistancia.getText());
                fuerza=Double.parseDouble(txtFuerza.getText()); 
                txtCarga2.setText(Operaciones.calcularCarga(carga1,distancia,fuerza));
            }
            else if(txtDistancia.getText().equals("")){
                carga1=Double.parseDouble(txtCarga1.getText());
                carga2=Double.parseDouble(txtCarga2.getText());
                fuerza=Double.parseDouble(txtFuerza.getText());
                txtDistancia.setText(Operaciones.calcularDistancia(carga1, carga2, fuerza));
            }
            else if(txtFuerza.getText().equals("")){
                carga1=Double.parseDouble(txtCarga1.getText());
                carga2=Double.parseDouble(txtCarga2.getText());
                distancia=Double.parseDouble(txtDistancia.getText());
                txtFuerza.setText(Operaciones.calcularFuerza(carga1, carga2, distancia));
            }
            else {
                carga1=Double.parseDouble(txtCarga1.getText());
                carga2=Double.parseDouble(txtCarga2.getText());
                distancia=Double.parseDouble(txtDistancia.getText());
                fuerza=Double.parseDouble(txtFuerza.getText());
                JOptionPane.showMessageDialog(null, "Deja una casilla vacia", "Error", WARNING_MESSAGE);
            }
        } 
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Verifica los valores ingresados", "ERROR", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonCalcularActionPerformed

    private void BotonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLimpiarActionPerformed
        pantallaLimpia = true;
        repaint();
        txtCarga1.setText("");
        txtCarga2.setText("");
        txtDistancia.setText("");
        txtFuerza.setText("");
    }//GEN-LAST:event_BotonLimpiarActionPerformed

    private void BotonLimpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLimpiar1ActionPerformed
        // TODO add your handling code here:
        Plano p = new Plano(this.panel);
        try {
            if((Double.parseDouble(txtCarga1.getText()))>0&&(Double.parseDouble(txtCarga2.getText()))>0){
                p.c1();
                pantallaLimpia=false;
            }
            else if((Double.parseDouble(txtCarga1.getText())<0)&&(Double.parseDouble(txtCarga2.getText())<0)){
                p.c2();
                pantallaLimpia=false;
            }
            else if((Double.parseDouble(txtCarga1.getText())<0)&&(Double.parseDouble(txtCarga2.getText())>0)){
                p.c3();
                pantallaLimpia=false;
            }
            else if((Double.parseDouble(txtCarga1.getText())>0)&&(Double.parseDouble(txtCarga2.getText())<0)){
                p.c4();
                pantallaLimpia=false;
            }
        } 
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Verifica los valores ingresados", "ERROR", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotonLimpiar1ActionPerformed

    private void conversionMedidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conversionMedidasActionPerformed
        //Ingresar a boton conversion de medidas
        MenuPrincipal menu = MenuPrincipal.getMenuPrincipal();
        menu.setVisible(false);
        
        ConversionMedidas con = ConversionMedidas.getConversionMedidas();
        con.setVisible(true);
    }//GEN-LAST:event_conversionMedidasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonLimpiar;
    private javax.swing.JButton BotonLimpiar1;
    private javax.swing.JButton botonCalcular;
    private javax.swing.JButton conversionMedidas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField txtCarga1;
    private javax.swing.JTextField txtCarga2;
    private javax.swing.JTextField txtDistancia;
    private javax.swing.JTextField txtFuerza;
    // End of variables declaration//GEN-END:variables
}
